### ISSUE TITLE
Moving Mouse along Edge from Small to Large Screen Breaks Link

### ISSUE THREAD

**Issue by merlinpatt** [bitgapp/Cursr#10]
### Describe the Bug/Issue

The smooth, proportional movement between different size screen breaks when moving along the part of the border that doesn't align.

### Steps to Reproduce

1. Create link between a small border and a large border with the small border on bottom
2. Move mouse upward along small screen's right edge
3. Continuing moving the mouse upward while also moving the mouse rightward
4. Upon moving up and right once you hit the top-right corner of the small screen, the mouse no longer has smooth movement between different size screens

### Expected Behavior

**Screenshots**

<img width="552" alt="Screen Shot 2021-08-16 at 15 16 17" src="https://user-images.githubusercontent.com/421960/129620138-35d594b3-67fa-491f-aa22-c3846d4b827a.png">

### Your Environment
 - OS details: MacOS Catalina 10.15.7 (19H1323)
 - Cursr Version: v1.3.1

**Comment by ragauskl** [comment]
Noted, will try to add fix in release tomorrow of v1.3.2

The fix probably still won't be 100% smooth as it's an issue on all platforms when linking borders that are linked by the OS as well, Cursr sets the new position, but the system keeps overriding it, there's a repeat event in Cursr, but that does not always help and I did not want to add more repeat events to interrupt mouse movement, this override of override sometimes causes unwanted behaviour, I'm still in search for a better solution that works on all platforms/if one is possible

**Comment by merlinpatt** [comment]
I think a couple options that could help with the issue would be

- give users the option to control repeating events under advanced settings
- allow a keyboard shortcut to be set to trigger the link action again

**Comment by ragauskl** [comment]
Good news - it wasn't the bug I thought it was, it was actually a bug within Cursr which is now fixed in v1.3.2 (at least from what I was able to replicate)

Could you let me know if that fixed it for you as well?

In terms of suggestions, there's very little wiggle room for messing with repeating/timeout events, if it happens in >100ms it starts to become very laggy/jumpy looking like. I thought of the settings one, but decided to try and spend some time on and off looking for solution, only as last resort I would want to add that, so it's in a backlog for now, if there will be more people interested in similar workaround(s) I'll look into adding it sooner rather than later

**Comment by ragauskl** [comment]
@merlinpatt  As there have been no further comments on the issue after the fix, I assume it's solved, I'll keep the issue open for couple more days and will close it if there won't be any new comments on the issue

**Comment by merlinpatt** [comment]
That seems to have fixed it so far. Thanks!

(Thought I had responded already, apologies)
