### ISSUE TITLE
'Unexpected error' after launch.

### ISSUE THREAD

**Issue by jacobcxdev** [bitgapp/Cursr#13]
### Describe the Bug/Issue

Cursr experiences an 'unexpected error' immediately after launching, and does not appear to work at all.

### Screenshots
![CleanShot 2021-11-29 at 15 59 40](https://user-images.githubusercontent.com/27970288/143901237-4b9f3794-b3bd-4008-b534-5c732c783a73.png)

### Your Environment
 - OS details: macOS Monterey 12.1 Beta
 - Cursr Version:  1.4.0 (1.4.0)

**Comment by ragauskl** [comment]
@jacobcxdev I know where the issue is, I've seen it before and fixed it on M1 mac and Hackintosh, I thought at least, looks like it does not work in all environment. It should be a quick fix, I'll release update tomorrow or day after ( as ideally I need to include something more than just this fix so users on other platforms also get an update for a reason)

**Comment by ragauskl** [comment]
@jacobcxdev v1.4.1 with fix is now released, the app might download itself but as error happens on launch it's possible that app might enter a bad state and it won't check for update, in that case you can download latest version from https://cursr.app or from [Github  Releases (link to .dmg)](https://github.com/bitgapp/Cursr/releases/download/v1.4.1/Cursr.dmg)

Could you let me know if issue is gone after update?

**Comment by jacobcxdev** [comment]
This issue is fixed; thank you.
