### ISSUE TITLE
Issue crossing cursor between monitors when CPU maxed out + my remedy

### ISSUE THREAD

**Issue by ricardosalta** [bitgapp/Cursr#18]
I've got 50 tabs open in Chrome, lots of extensions, plenty other apps open plus right now I'm also running a backup.

Even without the backup, Cursr was already giving me this problem, and occasionally in other days it happened as well under high cpu load.

While crossing between displays, I gotta do it very slow, or the cursor keeps being "pulled back", literally jumping back in its path. Surely a flow breaker. 

By the way, you have a setting "F "Disable Safety for Transitions", seems to be about this. But I tried it on or off, and it didn't solve the problem I was having.

So I wondered, and I tested something, and it worked, so I call it a remedy:

Using Process Hacker (but I think this can also be done with the default Windows Task Manager), I selected all 4 instances of Cursr.exe, right-clicked, and changed the priority to "Above Normal".

And boom. Problem gone. My CPU is toiling (not boiling) at 99.94% usage, but now Cursr works fine, no more issue.

Immediately I wonder if any app can set its own CPU priority. But since I'm not the developer I leave this question to you.

What I still wondered was what could I do to make the priority "upgrade" permanent on my own, so I ended up at this article which I haven't read yet but I leave it here: https://www.raymond.cc/blog/permanently-set-process-priority-in-windows-task-manager-with-prio/

One more thing: after I had already remedied this with this "trick" above, I opened the Cursr GUI to get your contact, and there was an error waiting for me.

"Can't monitor mouse
movements
Failed to attach listener to
system input, it took too
long and timed out.Please
report the issue on
Github/Cursr"

I suppose it was from before I applied my remedy.

Notes about the error message:

1) Shouldn't it show me the message right as the problem occurs even if I'm not with Cursr GUI open, such as with a system MsgBox or whatever it's called? Or a Windows notification actually. Whatever works, but not just inside the app when by chance I open it and otherwise wouldn't see it.

2) Although I could actually select the text of the error message, then right-clicking didn't give me an option to copy. I don't remember if I tried Ctrl+C, but anyway, right-click->copy should work.

3) There's a space missing before "Please".

That's it.

Thanks a ton for Cursr. I really dig it and I'm looking forward to what's to come.

Have a great Sunday!

Ricardo

![ApplicationFrameHost_UqAgT3yEJ1](https://user-images.githubusercontent.com/2092784/167288941-2d722299-5bac-4109-afd7-00d5016d5075.png)

**Comment by ragauskl** [comment]
Hey, thanks for submitting an issue for this, this will be helpful and I'll start looking into the issue in upcoming days.

**Comment by ragauskl** [comment]
Hey, thanks for submitting an issue for this, this will be helpful and I'll start looking into the issue in upcoming days, what I can say now is:

Cursr performance - As Cursr is built using mixed native and web technologies it will unlikely be as performant as purely native solution, so especially when CPU usage is already high, Cursr is more likely to react more slowly, which is why you might see behaviour like cursor being 'pulled back'. 

I'm always looking for ways to optimize it but for now performance improvement ideas (without making major rewriting of the application) have slowed down until I have more time on my hands for researching and messing around with Cursr.

The idea about setting priority is really good and fit for Cursr I think as Cursr interacts with mouse making it indeed more important than average process, thanks for sharing that, I never really had to change priority for application so it didn't occur to me to do that to Cursr before, but I'll definitely will look into adding that to next release with 'above average' priority and option to disable/change it.

Error "Can't monitor mouse movements" - If transitions are working or/and when you open map you can see the representation of cursor within the UI moving as you move the mouse you can safely dismiss the error.  I'm working on/looking for ways to make Cursr fail-proof aware if it successfully set up monitoring of system mouse, it has some gaps in this where it might be listening but some 'notifications/events' did not happen and it thinks it's not attached.  

And about notes on error messages:
1. System notifications are enabled for some things indeed, but not all of notifications/errors will be set to use system notifications if UI is hidden to not annoy the user where not necessary. If I remember correctly for this error reasoning was that it should not be happening in majority of cases and if it would happen users would notice that Cursr is not working and would open the app and then see the error anyways. But generally it does fall under category of important notifications/is similar to other ones that I've set to fall-back to system notification if hidden, not sure why I didn't think to add it there before, probably got distracted with other work, there's so much of it now I rarely find time to revisit things like this and think about it again until someone points it out or I stumble on it somehow.
2. Ctrl + C indeed should work, I believe that's why I left text as 'selectable', the right click context menu is not added as majority of native applications don't allow for this, usually you'll only see 'copy' option if it's an input field or if it's page in browser, which this is not (kind of, it is running UI using chromium so in browser, but it should look and feel more like software). But I do see how - if text is selectable/highlighted - one would expect it to also have right-click > copy option. I'll have a think of this and maybe instead of adding copy option, make text unelectable but add special button to 'export/copy' error, to paste into github or in email when reporting an issue, maybe with additional, already formatted, helpful context.

A bug report button is also planned within the app which would replace the need for copying error messages at all, I just don't currently have time to allocate for it, I will likely find some time for it in second half of the year.

3. Yep - noted, will adjust that

Thanks for all of the feedback, it will help to make Cursr more stable and a better experience for everyone, as like I mentioned I don't always catch all the things myself as mostly it works on computers I'm using for testing/development. Also it's useful to get opinion from someone with a fresh look on it, as I sometimes get carried away with main tasks at the time and keep delaying and/or forgetting about some other smaller bits

**Comment by ragauskl** [comment]
Oh also 'Disable Safety for Transitions' is for a bit different case, sometimes if Cursr feels unresponsive in terms that it does not want to go over a 'linked' border pair as if it's not there, then it might help it - as Cursr has some 'protection' in place to stop it from going crazy in case some positional calculations are wrong. It has happened before where cursor would start moving between linked borders rapidly back and forth, so to prevent that there are some delays/timeouts in place, and you can disable them to make Cursr a bit more responsive ( In future this should not be needed as I make Cursr more stable, but for now it is an option)

But in your case cursor actually jumps position which is issue of Cursr processing everything slowly and almost being out of sync with the system mouse, which also can lead to position calculation issues, so when you increased the priority Cursr was no longer slow and was in sync with the system, there are so many things happening so quick that smallest 1s lag in application can cause miscalculations, everything has to be done in as few milliseconds as possible for Cursr to work flawlessly

**Comment by ragauskl** [comment]
@ricardosalta on Windows Cursr will always have Above Normal priority now, with option to set even higher priority (for highest/realtime priority admin privileges would be required)

In any case anyone will be looking for similar behaviour on macOS or Linux - it is available however Cursr will have to be run with elevated access due to macOS and Linux not allowing app without admin access to elevate it's own priority
