### ISSUE TITLE
Feature Request: Disable when user-listed application is active

### ISSUE THREAD

**Issue by Mathsterk** [bitgapp/Cursr#22]
Just a feature request for disabling mouse transitions when a certain application is active, like a game, since some of them don't cooperate nicely with Cursr.
It could be implemented as a list of executables that disables cursr when they are active or running.

**Comment by ragauskl** [comment]
@Mathsterk This feature is already added to 'to-do' list and will be coming out, just unfortunately currently I have of list of other tasks with higher priorities so it will take a bit of time (trying to get those done in under 2 months but can't promise anything). You can expect it with next 'minor' version update or very soon after that :)

**Comment by ragauskl** [comment]
@Mathsterk In meantime you can use keyboard shortcut to quickly enable and disable Cursr when playing a game or using other application that Cursr does not work well with. Default keyboard shortcut is 'Shift+Alt+D' but you can change that in settings

**Comment by ragauskl** [comment]
@Mathsterk As I recently had to make a bug fix and make a new release anyways, I found some time to include this feature as well so it will be available in v1.4.10  ~tomorrow

**Comment by ragauskl** [comment]
@Mathsterk As I had some other bug fixes to do asap I decided to also find time to add some version of 'auto disable/enable' , there's no reliable/consistent way to do 'smart' detection of when Cursr should be disabled so I decided not to do it, instead make it simple by allowing user to define list of processes, if one of those processes will be in fullscreen mode and focused by user then cursr will automatically get disabled (and enabled once process is no longer in focus)

If user manually toggles Cursr it will stop any automatic enable/disable until app is reloaded, to avoid causing annoyances to user

You can manually list (what you can list will vary on platform, the input placeholder will have a hint as to what you need to enter) processes in 'General' settings section, for now due to time constraints it's only a manual input, but later on I'll add a selection from files and/or running processes

Also in case anyone uses Apps from Windows Store, those can't be detected at the moments as I can't get the window bounds/rectangle for it as it returns all 0s which is of no use. But until it doesn't bother anyone it's not a priority

Anyways, any bugs or issues or suggestion with the feature, let me know :)

**Comment by ragauskl** [comment]
Ah also if you get notification that update is available/downloaded and you restart the app but it does not start, download latest version from [official](https://cursr.app/) page again

Some people had this issue and it should now be resolved in v1.4.10

**Comment by Mathsterk** [comment]
Thank you for implementing it so fast, it has only been acting up in some full screen applications, so the lack of fancy features or detection doesn't bother me :)
And the update went smoothly, i'll make sure to test it and give some feedback if any issues occur, i'm not sure if i should close this or not, so feel free to close it if you feel like it should be closed.

**Comment by ragauskl** [comment]
No worries, it's been one of most requested features too so really wanted to get it done

I've linked few more users to this issue, so I'll keep it open for about a week in case anyone will have something to add relating to this issue/feature, but if there won't be any comments I'll close/mark this as done :)
