### ISSUE TITLE
Cursr does not work while Valorant is running

### ISSUE THREAD

**Issue by jbzdarkid** [bitgapp/Cursr#30]
### Describe the Bug/Issue
Valorant is a game by Riot which runs as admin. While it's running (even without focus), Cursr has no impact -- borders are treated as windows native settings.

### Steps to Reproduce

1. Install Valorant (https://playvalorant.com/en-us/)
2. Launch Valorant (from the riot client)
3. Run Cursr
4. Suffer

### Expected Behavior

Ideally, Cursr would be able to act while Valorant was running -- but even without, it would be good for it to act when valorant is in the background, or minimized.

### Your Environment
 - OS details: Windows 10 21H1 (19043.2311)
 - Cursr Version: 1.4.11 (although this has been true for a while)
 - License: Free, although it repros with the "Pro Trial" as well.

**Comment by ragauskl** [comment]
@jbzdarkid  That can be fixed by running Cursr as admin as well, this is due to the way Windows works, when something 'runs as admin' other non-admin applications cannot get/listen in on anything happening like mouse moving, therefore Cursr is not reacting, but if you run it as admin as well that will fix it

However Cursr will not work nicely if you're running fullscreen games that use mouse to control camera/view on the same screen that has edges linked to other edges (if the game does not reset mouse position to centre, so mouse will reach screen edge and if you linked it with other edge (especially of the same screen)  the game camera will start jumping back and forth/move around in unexpected way). -- If you'll experience this I suggest adding the game to Cursr 'Settings > Auto Disable' - that way Cursr will auto disable when Valorant is actively running in fullscreen mode and as soon as any other window gets activated or Valorant is minimized Cursr will enable itself back

If this does not resolve the issue let me know

**Comment by ragauskl** [comment]
Currently Cursr does not have an option to always start up as 'admin' so you'll need to do that manually for now (or create shortcut to Cursr that runs it as admin and place that to Windows startup - will need to google how to do that), but I'll look into adding in option within Cursr in next update or one after that

**Comment by jbzdarkid** [comment]
I tried to run Cursr as admin but it's still not helping. Even with Valorant minimized, borders are using the windows default.

**Comment by ragauskl** [comment]
Okay, it works with other games I've tested  so it might have something to do with how the game is written,  I'll download the game and see what could be causing the issue in upcoming days.

Could I ask if you run it in fullscreen mode or borderless? (still can be visually fullscreen but there's different information the window provides that Cursr can see)

**Comment by jbzdarkid** [comment]
I tried borderless and windowed, it didn't make a difference. Again, the odd thing is that it doesn't work even if it's windowed and minimized.

**Comment by ragauskl** [comment]
@jbzdarkid I've been doing some testing and could not replicate the problem, I added `C:\Riot Games\VALORANT\live\ShooterGame\Binaries\Win64\VALORANT-Win64-Shipping.exe` and it works as expected:
* When it's in 'Fullscreen' or 'Windowed Fullscreen' Cursr auto disables itself
* When another window is focused or Valorant is minimized Cursr auto enables itself

Also worth noting **once you manually enable/disable Cursr it will stop any further auto-toggle, for auto enable/disable to work again you need to restart Cursr**, this is so that manual changes don't get overridden unexpectedly 

But what's also interesting I set the game to just 'Windowed' mode (Cursr currently does not support auto enable/disable on windowed mode) and Cursr stays enabled with horizontal loop (right border of main display to left border) - Valorant works without a problem, where's other games camera start jumping around in unexpected way, this is probably because Valorant has some 'adjustment' mechanism in place (but that might apply only to Windowed mode, can't know for sure, but you can try running the game in Windowed mode just to check)

I have a few questions:
1. When you say 'suffer' what exactly happens besides Cursr border transitions not working?
2. When Cursr is running and you open Valorant, then minimize it and borders are using the windows default configuration - can you open Cursr window and check:
    *  if it's enabled or disabled? Is the toggle in top left corner on or off?
    * when you move the mouse around, do you see mouse icon moving around in the Cursr app as well?
 
    ![image](https://user-images.githubusercontent.com/9280160/206881305-6bd92003-c985-4677-9be2-44fead17200a.png)
