### ISSUE TITLE
Feature/Bug Request: Do not show the setting screen when launching from start up

### ISSUE THREAD

**Issue by ianjukes** [bitgapp/Cursr#35]
When my Mac first starts up, Cursr is the only app that is automatically started that I need to close the settings window for.

Behaviour for apps launched at startup is they should be hidden (menubar only).

**Comment by ragauskl** [comment]
I'm aware of this issue, Cursr is built to run as hidden on startup and this is a bug affecting macOS versions after one of the updates, because initially it used to work, my guess is this is an issue with underlying tool used for auto startup as similar issue happened before on windows and I've added workaround for that.

I'll be releasing v1.5.0 for beta testing in upcoming days and straight after that will be doing a patch update for v1.4.x which will include fix for this issue among few others

**Comment by ragauskl** [comment]
@ianjukes Apologies for the delay, I've released a fix in second update to 1.5.0 but forgot to mention it here, due to changes in my work plans I won't have time to make patch updates to 1.4.x and where possible issue fixes and feature requests are/will be included in 1.5.0 beta, if you don't want to download beta version of Cursr - stable public release will be made by 8th of May

**Comment by ianjukes** [comment]
> stable public release will be made by 8th of May

Hi @ragauskl -- just wondered if you have any update on the stable release?

**Comment by ragauskl** [comment]
@ianjukes  Hey Ian, within 1 month. On 8th of May I was not feeling comfortable with releasing stable yet and instead released another Beta update and decided to look for more beta testers as there were only 20 at the time and less than 10 provided feedback. 8th May to 10th Jun I had limited availability to get any work done, but now I'm back working on Cursr full time. I have some more feedback from Beta testers to work on but now next release will be a stable release

**Comment by ragauskl** [comment]
@ianjukes  This fix is now in stable v1.5.0 release, apologies for how long it took, I kept finding things to fix before I was comfortable with making a stable release of new KVM feature as it's a major change, almost another amount if not more work compared to what Cursr was before
