### ISSUE TITLE
Client keyboard experiences stuck key behavior

### ISSUE THREAD

**Issue by aschmahmann** [bitgapp/Cursr#53]
### Describe the Bug/Issue

When pressing Shift with a letter (say `A` and then releasing the shift quickly followed by the letter the lowercase letter will be repeated indefinitely).

This only occurs when using my keyboard with the remote client. Using a separate keyboard with that machine doesn't have the issue, nor does using the keyboard with the server.

### Steps to Reproduce

1. Navigate to the client
2. Open up a terminal
3. Press and hold Shift
4. Press `A`
5. Release Shift followed shortly by `A`
6. See lots of lowercase `A`s repeat themselves

### Expected Behavior

When your hands are off the keyboard keys stop printing

**Screenshots**

### Your Environment
 - OS details:
    - Server: Windows 11 x64
    - Client: Arch Linux (fairly fresh install)
 - Cursr Version: 1.6.6 (client and server)
 - License: Free
 - Keyboard and Mouse are Logitech wireless

### Additional Context

Maybe related, but if I unplug and switch the wireless dongle from the Windows machine to the Linux machine Cursr picks it up and mostly works (very cool), but my mouse on the client (now Windows) becomes invisible (I can see it moving/highlighting things) and certain keys like `Backspace` and `Enter` stop working (they work just fine on the now-server Linux).

Note: I tried disabling Wayland, it didn't help

**Comment by ragauskl** [comment]
Thank your for reporting the issue, I will look into fixing this with the next release v1.7.0

**Comment by ragauskl** [comment]
@aschmahmann  I've been trying to reproduce the issue to fix it but had no luck, if issue still persists after v1.7 for you could you enable Debug mode  in settings on both devices, reproduce the issue and send me compressed logs (there's button in settings as well to get them)

I also can't replicate the issue with mouse not being visible, I do know that there is list of issues related to Wayland and maybe just disabling Wayland still does not work quiet the same as not having it in first place/starting with X11. I don't have detailed knowledge of how it all works in detail. However I will be looking into Wayland support for 1.8+ and will try to make place for Wayland environment on my devices so I can test it .

But despite no luck with first 2 issues, the issue with Enter and some other keys not working is fixed in 1.7 that I'll release in next week or so

**Comment by aschmahmann** [comment]
Thanks, if you'd like me to test a beta/developer build let me know, otherwise will report back with the results post 1.7.

**Comment by ragauskl** [comment]
1.7 is now available in pre-release mode, to allow update to pre-release you'll need to enable 'Early Access' mode in 'General' settings and 'check for updates' in 'About' settings section.

Alternatively you can wait for 1.7 to be released in stable mode as soon as some users test it and I make sure it's stable.

**Comment by ragauskl** [comment]
1.7 is now released as stable, let me know if the issue still exists in 1.7

Regarding Wayland, I'll be working on adding support for it in 1.8

**Comment by aschmahmann** [comment]
Thanks @ragauskl, and apologies for taking so long to test. This looks like it's resolved the issue (i.e. I cannot reproduce using the example above like I could before).

Regarding some of the other issues I mentioned here (which probably could've been separate GitHub issues 😅)
- The issue with `Backspace` and `Enter` with a Windows client and Linux server also seems resolved.
- However, the mouse being hidden when switching the dongle to make the Linux machine is still present. Let me know if you'd like me to open a new issue for that, as I think we can close this issue.

**Comment by ragauskl** [comment]
I'm currently looking into similar issues so maybe it's not related to Wayland, so it should get fixed either with upcoming patches or if it's wayland related then with v1.8.

If you're okay waiting for updates then you don't have to open an issue, however if you'd like to get update as soon as a related patch or wayland support is out potentially fixing the issue then you can create a separate issue on this, as after every update I go over github and see where I can provide an update or close some issues. Otherwise I may forget to update you amongst many other things I need to get done.
