### ISSUE TITLE
Auto-disable doesn't work with Helldivers 2

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [bitgapp/Cursr#67]
### Describe the Bug/Issue

If I bypass #66 by manually adding the path to `helldivers2.exe` to the auto-disable, and then restart Cursr, it still doesn't auto-disable when that process launches.

The auto-disable works fine with VScode, so it seems specific to Helldivers and/or full-screen games.

![image](https://github.com/bitgapp/Cursr/assets/200/715e4756-8ace-4c02-b05a-53820bfacd61)

### Your Environment
 - OS details: Windows 11 **23H2** x64 
 - Cursr Version: **1.7.1**
 - License: Pro

**Comment by ragauskl** [comment]
It's unlikely issue with full-screen games as I've previously removed check for full-screen mode due to how differently it is sometimes done in different games. So as long as given process is focused Cursr should auto-disable. 

I'll do some quick testing with steam games I have and see if I can replicate the issue, if not I'll get Helldivers 2 and see if that replicates the issue and it's game specific issue. I'll see if I can find time to include a fix within next couple patches

**Comment by ragauskl** [comment]
I'm still working on the list of issues you've mentioned overall amongst some other things so apologies for the time it's taking.

For this particular issues I couldn't replicate it with Helldivers 2 and auto-disable was working as expected. I'll still revisit this after patch but in meantime I remembered there's option to ignore whole folder as well (described in description seen in original image but probably I need to make it more obvious as I missed it myself).

So you can try using just 'D:\SteamLibrary\steamapps\common\' and that should ignore all steam games if that's not an issue for you.

**Comment by ragauskl** [comment]
When testing helldivers I noticed that at least in title it has weird characters just print as a symbol with '?' in it, so maybe that's why a manual entry does not work as it doesn't capture some character that on windows system shows up as invisible character, but in some places it shows up as actually unrecognized character or sth like that. So ideally it should be selected from the Cursr dropdown of windows/processes available for selection.

I did change the encoding for reading the file name/path so maybe it will help, however on my end I could not replicate the issue with either of the formats used. In both cases it would auto-disable when Helldivers was active/focused process.

I also added additional line of debug log in 1.7.2, if you still experience this issues, enable debug mode and send me the logs after the issue occurred (can do it in one go with other issues if they still happen) and that may give me a better idea why it's not detecting the process.

**Comment by ELLIOTTCABLE** [comment]
I am unable to test this for a variety of life situations, right now; so I'm gonna close it unless I can return to actually test this behaviour against the newer releases. If someone else comes across the behaviour, feel free to comment!
